language: go
go: 
   - 1.5
   - 1.6 
   - 1.7 
before_script: 
    - export GOPATH="$HOME/gopath"
    - go get -d -v
    - make prepare
    - "export LD_LIBRARY_PATH=$PWD/libgit2/install/lib"
    - "export PKG_CONFIG_PATH=$PWD/libgit2/install/lib/pkgconfig"
script: 
   - make test
