allow_tabular: true
allow_url_revisit: false
allowed_domains:
- api.github.com
app:
  DashboardMode: false
  DebugMode: false
  ID: 0
  Title: ""
  VerboseMode: false
  fault_tolerant: false
async: false
base_dir: ""
cache_dir: ""
collection: null
collector:
  allow_url_revisit: false
  cache: null
  collector: null
  current_mode: ""
  filters: null
  ignore_robots_txt: false
  max_depth: 0
  modes: null
  proxy: null
  random_user_agent: false
  root_url: ""
  transport: null
  user_agent: ""
dashboard_mode: false
debug:
  config:
    export_enabled: false
    export_formats: null
    export_prefix_path: ""
    export_schema_only: false
    export_sections: null
    load_debug: false
    load_error_on_unmatched_keys: false
    load_verbose: false
  tachymeter:
    async: false
    enabled: false
    export:
      backup_mode: false
      backup_prefix: ""
      backup_suffix: ""
      basename: ""
      buffer_size: 0
      enabled: false
      encoding: ""
      ensure_dir: false
      ensure_dir_recursively: false
      export_dir: ""
      format: ""
      overwrite: false
      prefix_path: ""
      split_at: 0
    histogram_bins: 0
    sample_size: 0
debug_mode: false
detect_charset: false
detect_mime_type: false
detect_tabular_data: false
disallowed_domains: null
export_dir: ""
fault_tolerant: false
filters: null
force_dir: false
force_dir_recursive: false
hooks:
  enabled: true
  registry:
    default:
      data_ql: null
      has_prefix: ""
      has_suffixslug: ""
      headers: null
      identifier: default
      mixed: null
      pattern_url: ""
      printer:
        colorize: false
        format: tabular-grid
      slicer: null
      slug: ""
      writer:
        basename: colly
        concurrent: true
        formats:
        - yaml
        - json
        - csv
        prefix_path: ./shared/exports
        split: true
        split_at: 2500
    repos:
      data_ql: null
      has_prefix: ""
      has_suffixslug: ""
      headers: null
      identifier: repos
      mixed: null
      pattern_url: /repos/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)$
      printer:
        colorize: false
        format: tabular-grid
      slicer:
        columns:
          cap: 0
          expr: '[::]'
          lower: 0
          upper: 0
        headers:
        - id
        - full_name
        - description
        - language
        - stargazers_count
        - watchers_count
        - owner_login
        - owner_id
        rows:
          cap: 0
          expr: ""
          lower: 0
          upper: 0
      slug: ""
      writer: null
    starred:
      data_ql: null
      has_prefix: ""
      has_suffixslug: ""
      headers: null
      identifier: starred
      mixed: null
      pattern_url: /users/([a-zA-Z0-9\-_]+)/starred
      printer:
        colorize: false
        format: tabular-grid
      slicer:
        columns:
          cap: 0
          expr: '[::]'
          lower: 0
          upper: 0
        headers:
        - id
        - full_name
        - description
        - language
        - owner_id
        - stargazers_count
        - updated_at
        rows:
          cap: 0
          expr: ""
          lower: 0
          upper: 0
      slug: ""
      writer: null
    users:
      data_ql: null
      has_prefix: ""
      has_suffixslug: ""
      headers: null
      identifier: users
      mixed: null
      pattern_url: /users/([a-zA-Z0-9\-_]+)$
      printer:
        colorize: false
        format: tabular-grid
      slicer:
        columns:
          cap: 0
          expr: '[::]'
          lower: 0
          upper: 0
        headers:
        - id
        - login
        - avatar_url
        - blog
        - created_at
        - hireable
        - following
        - followers
        rows:
          cap: 0
          expr: ""
          lower: 0
          upper: 0
      slug: ""
      writer: null
identifier: 1
ignore_robots_txt: true
inspect:
  inspect:
    struct:
      details:
        map: null
        names: null
        values: null
      has_zero: false
      is_struct: false
      is_zero: false
      name: ""
logs_dir: ""
max_body_size: 10485760
max_depth: 0
outputs:
  base_dir: ""
  cache_dir: ""
  export_dir: ""
  force_dir: false
  force_dir_recursive: false
  logs_dir: ""
  xdg_base_dir: ""
parse_http_error_response: false
random_user_agent: false
title: ""
useJsonParser: json
user_agent: colly - https://github.com/sniperkit/colly/pkg
verbose_mode: false
xdg_base_dir: ""
