package tachymeter

const (
	PACKAGE_VERSION = "0.0.1"
)

const (
	TACHYMETER_DEFAULT_SAMPLE_CAPACITY   int  = 4
	TACHYMETER_DEFAULT_HISTOGRAM_BUCKETS int  = 10
	TACHYMETER_DEFAULT_SAFE_MODE         bool = false
)
