[[pluck]]
name = "row"
activators = [ "row", "[" ]
deactivator = "]"
limit = 1

[[pluck]]
name = "rows"
activators = [ "rows", "[" ]
deactivator = "]"
limit = 1

[[pluck]]
name = "col"
activators = [ "col", "[" ]
deactivator = "]"
limit = 1

[[pluck]]
name = "cols"
activators = [ "cols", "[" ]
deactivator = "]"
limit = 1

[[pluck]]
name = "row"
activators = [ "row", "(" ]
deactivator = ")"
limit = 1

[[pluck]]
name = "rows"
activators = [ "rows", "(" ]
deactivator = ")"
limit = 1

[[pluck]]
name = "col"
activators = [ "col", "(" ]
deactivator = ")"
limit = 1

[[pluck]]
name = "cols"
activators = [ "cols", "(" ]
deactivator = ")"
limit = 1