xdg_base_dir = "/Users/lucmichalski/.config"

[[plucker]]
  name = "rows"
  activators = ["rows", "["]
  permanent = 0
  deactivator = "]"
  limit = -1
  maximum = 0
  patterns = [",", ":"]
  [plucker.match]
    mode = ""
    separator = ""
    split = false
    phrase = ""

[[plucker]]
  name = "cols"
  activators = ["cols", "["]
  permanent = 0
  deactivator = "]"
  limit = -1
  maximum = 0
  [plucker.match]
    mode = ""
    separator = ""
    split = false
    phrase = ""

[[plucker]]
  name = "unique_row"
  activators = ["row", "["]
  permanent = 0
  deactivator = "]"
  limit = 0
  maximum = 0
  [plucker.match]
    mode = ""
    separator = ""
    split = false
    phrase = ""

[[plucker]]
  name = "unique_col"
  activators = ["col", "["]
  permanent = 0
  deactivator = "]"
  limit = 0
  maximum = 0
  [plucker.match]
    mode = ""
    separator = ""
    split = false
    phrase = ""
