xdg_base_dir: /Users/lucmichalski/.config
plucker:
- name: rows
  activators:
  - rows
  - '['
  permanent: 0
  deactivator: ']'
  limit: -1
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns:
  - ','
  - ':'
  whitelist: []
  blacklist: []
- name: cols
  activators:
  - cols
  - '['
  permanent: 0
  deactivator: ']'
  limit: -1
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns: []
  whitelist: []
  blacklist: []
- name: unique_row
  activators:
  - row
  - '['
  permanent: 0
  deactivator: ']'
  limit: 0
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns: []
  whitelist: []
  blacklist: []
- name: unique_col
  activators:
  - col
  - '['
  permanent: 0
  deactivator: ']'
  limit: 0
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns: []
  whitelist: []
  blacklist: []
