xdg_base_dir: /Users/lucmichalski/.config
plucker:
- name: find_package
  activators:
  - find_package
  - (
  permanent: 0
  deactivator: )
  limit: -1
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns:
  - CONFIG
  - REQUIRED
  whitelist: []
  blacklist: []
- name: hunter_add_package
  activators:
  - hunter_add_package
  - (
  permanent: 0
  deactivator: )
  limit: -1
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns: []
  whitelist: []
  blacklist: []
- name: set_property
  activators:
  - set_property
  - (
  permanent: 0
  deactivator: )
  limit: -1
  match:
    mode: ""
    separator: ""
    split: false
    phrase: ""
  patterns: []
  whitelist: []
  blacklist: []
